---
###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

# tasks file for print_hc_buffer
###########################################################################
# skeleton for HZSPRNT
###########################################################################
- name: Send JCL template
  block:
    - ansible.builtin.set_fact:
        eager_role_path: '{{ role_path }}'

    - ansible.builtin.include_role:
        name: send-template
      vars:
        path: '{{ eager_role_path }}/templates/HZSPRINT.J2'

    - name: Get expiring certs report for {{ hc_check }}
      ibm.ibm_zos_core.zos_job_submit:
        src: '{{ uss_file_path }}/HZSPRINT.J2'
        location: USS
      register: hc_job_output
      ignore_errors: true

    - name: Set job id fact used in this playbook
      set_fact:
        submit_job_id: "{{ hc_job_output.results[0]['jobs'][0]['job_id'] }}"

    - name: Fact `submit_job_id` set with value
      debug:
        msg: "{{ submit_job_id }}"

    - name: Query submitted job by job_id.
      ibm.ibm_zos_core.zos_job_query:
        job_id: "{{ submit_job_id }}"
      register: query_job
