---
###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

# tasks file for issue_operator_cmd

##########################################################################
# Issue zos command
##########################################################################
- name: "{{ issue_operator_cmd_task_description }}"
  ibm.ibm_zos_core.zos_operator:
    cmd: "{{ issue_operator_cmd_command }}"
