
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:

    - name: Run z/OS TSO command(s).
      ibm.ibm_zos_core.zos_tso_command:
        commands: 
          "{{ zos_tso_command.split('\n') | default(\"LISTCAT ENT('SYS1.PARMLIB') ALL\") }}"
      register: command

    - name: "Print results from command(s). Click on the output and go to the 'JSON' tab to show more output."
      debug:
        var: command.output