---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  vars:
    zos_operator_commands: "{{ zos_operator_commands_survey.split('\n') | default(\"D M=CPU\") }}"
  environment: "{{ environment_vars }}"
  tasks:
    - block:
      - name: Submit z/OS operator command(s).
        zos_operator:
          cmd: "{{ zos_operator_commands }}"
        register: result_zos_operator

      always:
      - name: Response from operator command(s).
        debug:
          msg: "{{ result_zos_operator }}"