---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  tasks:
    - block:
      - name: Submit z/OS operator command.
        zos_operator:
          cmd: "{{ zos_operator_command_survey | default(\"D M=CPU\")  }}"
        register: result_zos_operator

      always:
      - name: Response from operator command.
        debug:
          msg: "{{ result_zos_operator }}"