---
- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    ds_name: "{{ ds_name | default('IBMUSER.ANSIB.DATASET') }}"
    dest_path: "{{ dest_path | default('/tmp/data_set') }}"
  tasks:
    
    - name: Create a sequential data set for demonstration purposes.
      zos_data_set:
        name: "{{ ds_name }}"
        type: seq
        state: present
        replace: true
        format: fb
        record_length: 100
        size: 5M
      register: result

    - name: Remove old /tmp/HELLO if it exists already, for idempotency.
      file:
        path: "/tmp/HELLO"
        state: absent
      register: result

    - name: Copy HELLO.jcl from project to USS file.
      zos_copy:
        src: "HELLO.jcl"
        dest: "/tmp/HELLO"
      register: result

    - name: Copy the USS file to the sequential data set.
      zos_copy:
        src: "/tmp/HELLO"
        dest: "{{ ds_name }}"
        remote_src: true
      register: result

    - name: Fetch the created sequential data set and store in {{ dest_path }}.
      zos_fetch:
        src: "{{ ds_name }}"
        dest: "{{ dest_path }}"
        flat: true

- hosts: localhost
  gather_facts: false
  tasks:

    - name: Get copied data set.
      slurp: "{{ dest_path }}"
      register: ds_contents

    - name: Print copied data set's contents from Linux's side.
      debug:
        msg: "{{ ds_contents['content'] | b64decode | regex_replace('\\n', '\n') }}"