---
###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

# tasks file for issue_operator_cmd

##########################################################################
# Issue zos command
##########################################################################
- name: "{{ issue_tso_cmd_task_description }}"
  ibm.ibm_zos_core.zos_tso_command:
    commands: "{{ issue_tso_cmd_command }}"
