###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    owner_id: "{{ owner_id_survey | default('IBMUSER') }}"
    cert_label: "{{ cert_label_survey | default('TESTCA') }}"
    cn: '{{ cert_label }}'
    ou: "{{ ou_survey | default('ANSIBLE CORE') }}"
    country: "{{ country_survey | default('US') }}"
    keyring: "{{ keyring_survey | default('SharedRing1') }}"
    expiry_date: "{{ expiry_date_survey | default('') }}"
    check_name: "{{ check_name_survey | default('IBMRACF,RACF_CERTIFICATE_EXPIRATION') }}"

  tasks:
    - block:
        - include_role:
            name: issue_tso_cmd
          vars:
            task_description: 'Create a new keyring'
            command:
              - RACDCERT ADDRING({{keyring}}) ID({{owner_id}})
              - RACDCERT LISTRING({{keyring}}) ID({{owner_id}})
      ignore_errors: true

    - include_role:
        name: issue_tso_cmd
      vars:
        task_description: 'Create new CA cert and connect to keyring'
        command:
          - RACDCERT GENCERT CERTAUTH KEYUSAGE(CERTSIGN) SUBJECTSDN(CN('{{cn}}') OU('{{ou}}') C('{{country}}')) WITHLABEL('{{cert_label}}') NOTAFTER(DATE({{expiry_date}}))
          - RACDCERT ID({{owner_id}}) CONNECT(CERTAUTH LABEL('{{cert_label}}') RING({{keyring}}))
      when: not expiry_date == ''

    - include_role:
        name: issue_tso_cmd
      vars:
        task_description: 'Create new CA cert and connect to keyring'
        command:
          - RACDCERT GENCERT CERTAUTH KEYUSAGE(CERTSIGN) SUBJECTSDN(CN('{{cn}}') OU('{{ou}}') C('{{country}}')) WITHLABEL('{{cert_label}}')
          - RACDCERT ID({{owner_id}}) CONNECT(CERTAUTH LABEL('{{cert_label}}') RING({{keyring}}))
      when: expiry_date == ''

    - include_role:
        name: issue_operator_cmd
      vars:
        task_description: 'Run Health Checker'
        command: "F HZSPROC,RUN,CHECK=({{check_name}})"
