---
- name: Generate an expired X.509 certificate.
  hosts: localhost
  gather_facts: false
  become: false
  tasks:

    - name: Generate expired certificate on controller.
      community.crypto.x509_certificate:
        path: "{{ playbook_dir }}/expired_cert/expired_cert.pem"
        privatekey_path: "{{ playbook_dir }}/expired_cert/expired_key.pem"
        csr_path: "{{ playbook_dir }}/expired_cert/expired_csr.pem"
        provider: selfsigned
        selfsigned_not_after: "20000101000000Z"

    - name: Copy expired cert contents to folder on z/OS host.
      copy:
        src: "{{ playbook_dir }}/expired_cert/"
        dest: /u/ibmuser/expired_cert/
        
