---
- name: Generate an expired X.509 certificate.
  hosts: localhost
  gather_facts: false
  become: false
  tasks:

    - name: Generate private key.
      community.crypto.openssl_privatekey:
        path: "{{ playbook_dir }}/expired_cert/expired_key.pem"

    - name: Generate expired certificate on controller.
      community.crypto.x509_certificate:
        path: "{{ playbook_dir }}/expired_cert/expired_cert.pem"
        privatekey_path: "{{ playbook_dir }}/expired_cert/expired_key.pem"
        provider: selfsigned
        selfsigned_not_before: +0s
        selfsigned_not_after: +1s

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    owner_id: "{{ owner_id_survey | default('IBMUSER') }}"
  tasks:

    - name: Copy expired cert contents to folder on z/OS host.
      copy:
        src: "{{ playbook_dir }}/expired_cert/"
        dest: "/u/{{ owner_id }}/expired_cert/" 

    - name: Copy the USS file to a sequential data.
      zos_copy:
        src: "/u/{{ owner_id }}/expired_cert/expired_cert.pem"
        dest: "{{ owner_id }}.CERTS.EXPIRED"
        remote_src: true
        force: true
      register: copy_to_ds

    - name: Response for copying expired_cert.pem to data set.
      debug:
        var: copy_to_ds
