###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

- name: List certificates via TSO commands.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    cert_type: "{{ cert_type_survey | default('SITE') }}"
    cert_label: "{{ cert_label_survey | default('TEST SITE') }}"
    owner_id: "{{ owner_id_survey | default('') }}"

  tasks:
    - block:
      - name: 'Displaying cert {{ cert_label }}.'
        ibm.ibm_zos_core.zos_tso_command:
          commands: "RACDCERT {{ 'ID(' + owner_id + ')' if cert_type == 'USER' else cert_type }} LIST(LABEL('{{ cert_label }}'))"
        register: list_cert
        changed_when: false

      always:
        - name: Print results from list USER cert command.
          ansible.builtin.debug:
            var: list_cert.output[0].content
