###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

- hosts: zos_host
  collections:
    - ibm.ibm_zos_core
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    # owner_id: 'OMVSADM'
    # cert_type: 'USER'
    # cert_label: 'ANDY SSL'

    # cert_type: 'CERTAUTH'
    # cert_label: 'ANDY CA'

    cert_type: "{{ cert_type_survey | default('SITE') }}"
    cert_label: "{{ cert_label_survey | default('TEST SITE') }}"

  tasks:
    - block:
      - name: 'Displaying cert {{cert_label}}'
        ibm.ibm_zos_core.zos_tso_command:
          commands: "RACDCERT ID({{ owner_id}}) LIST(LABEL('{{cert_label}}'))"
        when: cert_type == 'USER'
        register: list_user_cert

      - name: 'Displaying cert {{cert_label}}'
        ibm.ibm_zos_core.zos_tso_command:
          commands: "RACDCERT CERTAUTH LIST(LABEL('{{cert_label}}'))"
        when: cert_type == 'CERTAUTH'
        register: list_certauth

      - name: 'Displaying cert {{cert_label}}'
        ibm.ibm_zos_core.zos_tso_command:
          commands: "RACDCERT SITE LIST(LABEL('{{cert_label}}'))"
        when: cert_type == 'SITE'
        register: list_site_cert

      always:
        - name: "Print results from list cert command. Click on the output and go to the 'JSON' tab to show more output."
          debug:
            msg: "{{ list_user_cert.output[0].content if list_user_cert is defined else list_certauth.output[0].content if list_certauth is defined else list_site_cert.output[0].content if list_site_cert is defined }}"
