###############################################################################
# © Copyright IBM Corporation 2020, 2021
###############################################################################

- name: Search for expiring certificates and renew them.
  hosts: zos_host
  gather_facts: false
  environment: "{{ environment_vars }}"
  vars:
    cert_label: "{{ cert_label_survey }}"
    cert_type: "{{ cert_type_survey }}"
    sign_with: "{{ sign_with_survey | default(omit) }}"
    sign_label: "{{ sign_label_survey | default(' ') }}"
    owner_id: "{{ owner_id_survey }}"
    keyring_name: "{{ keyring_name_survey }}"

    cert_found: false
    today: ''

  tasks:
    - name: Create temporary directory to store bank files.
      ansible.builtin.tempfile:
        state: directory
      register: playbook_tmp_dir

    - name: Check if any certificates are expiring and renew them if necessary via TSO commands.
      vars:
        uss_file_path: '{{ playbook_tmp_dir.path }}'
      block:
        - name: Run health check via operator command.
          ansible.builtin.include_role:
            name: issue_operator_cmd
          vars:
            issue_operator_cmd_task_description: 'Run Health Checker'
            issue_operator_cmd_command: "F HZSPROC,RUN,CHECK=(IBMRACF,RACF_CERTIFICATE_EXPIRATION)"
          changed_when: false

        - name: Print health check.
          ansible.builtin.include_role:
            name: print_hc_buffer
          vars:
            print_hc_buffer_hc_check: 'IBMRACF,RACF_CERTIFICATE_EXPIRATION'

        - name: Search report for {{ cert_label }}.
          ansible.builtin.set_fact:
            cert_found: true
          with_items: "{{ hc_job_output.jobs.0.ddnames }}"
          when: item.content is search(cert_label)

        - name: Print found expiring cert.
          ansible.builtin.debug:
            msg: "{{ cert_label }} expiring - {{ cert_found }}"

        - name: Get date.
          ansible.builtin.command: "date '+%b%d%y'"
          register: date_result
          when: cert_found
          changed_when: false

        - name: Set 'today' variable with output from previous task.
          ansible.builtin.set_fact:
            today: "{{ date_result.stdout }}"
          when: cert_found

        - name: Back up current certificate when not USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Back up current certificate'
            issue_tso_cmd_command:
              - RACDCERT EXPORT(LABEL('{{ cert_label }}'))  DSN('{{ owner_id }}.CERT.{{ cert_type }}.BACKUP.{{ today }}') {{ cert_type }}
              - RACDCERT CHECKCERT('{{ owner_id }}.CERT.{{ cert_type }}.BACKUP.{{ today }}')
          when: cert_found and not cert_type == 'USER'

        - name: Back up current certificate when USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Back up current certificate'
            issue_tso_cmd_command:
              - RACDCERT EXPORT(LABEL('{{ cert_label }}')) ID({{ owner_id }})  DSN('{{ owner_id }}.CERT.{{ cert_type }}.BACKUP.{{ today }}')
              - RACDCERT CHECKCERT('{{ owner_id }}.CERT.{{ cert_type }}.BACKUP.{{ today }}')  ID({{ owner_id }})
          when: cert_found and cert_type == 'USER'

        - name: Rekey and Generate new cert request when not USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Rekey and Generate new cert request for {{ cert_type }}'
            issue_tso_cmd_command:
              - RACDCERT {{ cert_type }} REKEY(LABEL('{{ cert_label }}')) WITHLABEL('{{ cert_label }}-NEW')
              - RACDCERT {{ cert_type }} LIST(LABEL('{{ cert_label }}-NEW'))
              - RACDCERT {{ cert_type }} GENREQ (LABEL('{{ cert_label }}-NEW')) DSN('{{ owner_id }}.CSR.{{ cert_type }}.{{ today }}')
              - RACDCERT {{ cert_type }} DELETE(LABEL('{{ cert_label }}'))
          when: cert_found and not cert_type == 'USER'

        - name: Rekey and Generate new cert request when USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Rekey and Generate new cert request for {{ cert_type }}'
            issue_tso_cmd_command:
              - RACDCERT REKEY(LABEL('{{ cert_label }}')) WITHLABEL('{{ cert_label }}-NEW') ID({{ owner_id }})
              - RACDCERT ID({{ owner_id }}) LIST(LABEL('{{ cert_label }}-NEW'))
              - RACDCERT GENREQ (LABEL('{{ cert_label }}-NEW')) ID({{ owner_id }}) DSN('{{ owner_id }}.CSR.{{ cert_type }}.{{ today }}')
              - RACDCERT ID({{ owner_id }}) DELETE(LABEL('{{ cert_label }}'))
          when: cert_found and cert_type == 'USER'

        - name: Install and connect local cert when sign_label is not empty and not USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Install and connect local cert for {{ cert_type }}'
            issue_tso_cmd_command:
              - RACDCERT {{ cert_type }} GENCERT('{{ owner_id }}.CSR.{{ cert_type }}.{{ today }}') SIGNWITH({{ sign_with }} LABEL('{{ sign_label }}'))
              - RACDCERT {{ cert_type }} ALTER(LABEL('{{ cert_label }}-NEW')) NEWLABEL('{{ cert_label }}')
              - RACDCERT ID({{ owner_id }}) CONNECT({{ cert_type }} LABEL('{{ cert_label }}') RING({{ keyring_name }}) DEFAULT USAGE(PERSONAL))
          when: cert_found and not sign_label == ' ' and not cert_type == 'USER'

        - name: Install and connect local cert when sign_label is not empty and USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Install and connect local cert for {{ cert_type }}'
            issue_tso_cmd_command:
              - RACDCERT ID({{ owner_id }}) GENCERT('{{ owner_id }}.CSR.{{ cert_type }}.{{ today }}') SIGNWITH({{ sign_with }} LABEL('{{ sign_label }}'))
              - RACDCERT ID({{ owner_id }}) ALTER(LABEL('{{ cert_label }}-NEW')) NEWLABEL('{{ cert_label }}')
              - RACDCERT ID({{ owner_id }}) CONNECT(LABEL('{{ cert_label }}') RING({{ keyring_name }}) DEFAULT USAGE(PERSONAL))
          when: cert_found and not sign_label == ' ' and cert_type == 'USER'

        - name: Install and connect local cert when sign_label is empty and not USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Install and connect self-signed cert for {{ cert_type }}'
            issue_tso_cmd_command:
              - RACDCERT {{ cert_type }} GENCERT('{{ owner_id }}.CSR.{{ cert_type }}.{{ today }}') SIGNWITH({{ sign_with }} LABEL('{{ cert_label }}NEW'))
              - RACDCERT {{ cert_type }} ALTER(LABEL('{{ cert_label }}-NEW')) NEWLABEL('{{ cert_label }}')
              - RACDCERT ID({{ owner_id }}) CONNECT({{ cert_type }} LABEL('{{ cert_label }}') RING({{ keyring_name }}) DEFAULT USAGE(PERSONAL))
          when: cert_found and sign_label == ' ' and not cert_type == 'USER'

        - name: Install and connect local cert when sign_label is empty and USER cert via TSO commands.
          ansible.builtin.include_role:
            name: issue_tso_cmd
          vars:
            issue_tso_cmd_task_description: 'Install and connect self-signed cert for {{ cert_type }}'
            issue_tso_cmd_command:
              - RACDCERT ID({{ owner_id }}) GENCERT('{{ owner_id }}.CSR.{{ cert_type }}.{{ today }}') SIGNWITH({{ sign_with }} LABEL('{{ cert_label }}NEW'))
              - RACDCERT ID({{ owner_id }}) ALTER(LABEL('{{ cert_label }}-NEW')) NEWLABEL('{{ cert_label }}')
              - RACDCERT ID({{ owner_id }}) CONNECT(LABEL('{{ cert_label }}') RING({{ keyring_name }}) DEFAULT USAGE(PERSONAL))
          when: cert_found and sign_label == ' ' and cert_type == 'USER'

        - name: Run health check via operator command.
          ansible.builtin.include_role:
            name: issue_operator_cmd
          vars:
            issue_operator_cmd_task_description: 'Run Health Check'
            issue_operator_cmd_command: "F HZSPROC,RUN,CHECK=(IBMRACF,RACF_CERTIFICATE_EXPIRATION)"
          when: cert_found

      always:
        - name: Delete the temporary directory.
          ansible.builtin.file:
            path: "{{ playbook_tmp_dir.path }}"
            state: absent
