- name: Stage pkcs12 package on controller.
  hosts: localhost
  gather_facts: true
  tasks:

    - name: Copy z/OS certificate data to controller.
      ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ item.dest }}"
        mode: '600'
      loop:
        - { content: "{{ zos_cert }}", dest: ~/zos_cert.pem }
        - { content: "{{ zos_cert_key }}", dest: ~/zos_cert_private_key.pem }

    - name: Create passphrase with PKCS#12 passphrase.
      ansible.builtin.set_fact:
        pkcs12_passphrase: "{{ lookup('password', '/dev/null', chars=['ascii_letters'], length=12) }}"

    - name: Create file from passphrase for later use.
      ansible.builtin.copy:
        content: "{{ pkcs12_passphrase }}"
        dest: ~/pkcs12-passphrase.txt
        mode: '600'

    - name: Install expect and dnf module dependencies.
      ansible.builtin.pip:
        name: [pexpect>=3.3, python3-dnf]

    - name: Install higher openssl version.
      ansible.builtin.dnf:
        name: openssl>=3.0.0

    - name: Generate PKCS#12 file from private key and certificate.
      ansible.builtin.expect:
        command: openssl pkcs12 -legacy -export -out ~/keyStore.p12 -inkey ~/zos_cert_private_key.pem -in ~/zos_cert.pem
        creates: ~/keyStore.p12
        responses:
          "Enter Export Password:":
            - "{{ pkcs12_passphrase }}"
          "Verifying - Enter Export Password:":
            - "{{ pkcs12_passphrase }}"
